name: CI

on:
  push:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Setup NodeJS
      uses: actions/setup-node@v1
    - name: Setup Ruby
      uses: actions/setup-ruby@v1
    - name: Install Dependencies
      run: npm install
    - name: Check format
      run: npm run check-format
    - name: Run test
      run: npm test
    - name: build
      run: make
    - name: deploy
      uses: peaceiris/actions-gh-pages@v2
      env:
        ACTIONS_DEPLOY_KEY: ${{ secrets.ACTIONS_DEPLOY_KEY }}
        PUBLISH_BRANCH: gh-pages
        PUBLISH_DIR: ./public
