name: CI

on:
  push:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Setup NodeJS
      uses: actions/setup-node@v1
    - name: Setup Ruby
      uses: actions/setup-ruby@v1
    - name: Install Dependencies
      run: npm install
    - name: Check format
      run: npm run check-format
    - name: Run test
      run: npm test
    - name: build
      run: make
    - name: deploy
      uses: peaceiris/actions-gh-pages@v3
      if: ${{ github.ref == 'refs/heads/master' }}
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./public
