name: CI

on:
  push:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Setup NodeJS
      uses: actions/setup-node@v1
    - name: Install Dependencies
      run: npm install
    - name: Check format
      run: npm run nheck-format
    - name: Run test
      run: npm test
